# stage1 - build react app first 
FROM node:16-alpine as build
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json", "./"]
RUN npm install --production
COPY . /usr/src/app
RUN npm run build

# stage 2 - build the final image and copy the react build files
FROM nginx:stable-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 9001
CMD ["nginx", "-g", "daemon off;"]