version: "3.4"

services:
  timetrackerserver:
    image: timetrackerserver
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - "database"
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    ports:
      - ${PORT}:${PORT}

  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - .env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"

volumes:
  database-data: # named volumes can be managed easier using docker-compose
