version: "3.4"

services:
  timetrackerserver:
    image: timetrackerserver
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      PORT: ${PORT}
      NODE_ENV: production

    ports:
      - ${PORT}:${PORT}
  
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose