version: "3.4"

services:
  api:
    image: api
    build:
      context: api
      dockerfile: ./Dockerfile
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - "database"
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    ports:
      - ${PORT}:${PORT}

  database:
    image: postgres # use latest official postgres version
    env_file:
      - .env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"

  dev-client:
    image: dev-client
    build:
      context: client
      dockerfile: ./Dockerfile
    volumes:
      - "./client:/usr/src/app"
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_BASE_URL=api:9002

  server:
    image: server
    build:
      context: client
      dockerfile: ./Dockerfile.prod
    volumes:
      - "./client:/usr/src/app"
    ports:
      - 9001:9001

volumes:
  database-data: # named volumes can be managed easier using docker-compose
